# golangci-lint configuration
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    min-confidence: 0.8
  cyclop:
    max-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/jocham/mongo-essential
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - cyclop
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - copyloopvar
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-files:
    - "examples/main.go"
    - "examples/library-usage-example.go"
  exclude-dirs:
    - examples
  exclude-rules:
    - path: examples/
      linters:
        - typecheck
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
        - dupl

  exclude-use-default: false
  exclude:
    # Allow blank imports for side effects
    - "should not use blank imports"
    
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
