name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Trigger go.dev to update the package documentation
  update-pkg-go-dev:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - name: Update pkg.go.dev
        run: |
          curl -X POST "https://proxy.golang.org/github.com/jocham/mongo-essential/@v/${{ github.ref_name }}.info"
          sleep 5
          curl "https://pkg.go.dev/github.com/jocham/mongo-essential@${{ github.ref_name }}"